curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query{\n  getTodos(sortBy:priority, direction: ASC){\n    description\n    priority\n  \n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query{\n  getTodos{\n    description\n    priority\n  \n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query{\n  getTodos(sortBy:createdAt, direction: DESC){\n    description\n    priority\n  \n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query{\n  getCompletedTodos{\n    description\n    priority\n  \tcompleted\n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"mutation{\n  createTodo(description:\"Test\", priority: 1){\n    success,\n    errorMessage\n    data{\n      description\n    }\n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"mutation{\n  createTodo(description:\"Test without priority\"){\n    success,\n    errorMessage\n    data{\n      description\n    }\n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"mutation{\n  updateTodo(id:\"56e29274-ce4f-4206-9f68-f7779e273de5\", priority: 5){\n    success,\n    errorMessage\n    data{\n      description\n    }\n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"mutation{\n  markTodoAsCompleted(id:\"56e29274-ce4f-4206-9f68-f7779e273de5\"){\n    success,\n    errorMessage\n    data{\n      description\n    }\n  }\n}\n"}' --compressed
curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"mutation{\n  deleteTodo(id:\"56e29274-ce4f-4206-9f68-f7779e273de5\"){\n    success,\n    errorMessage\n    data{\n      description\n    }\n  }\n}\n"}' --compressed
